### ISSUE TITLE
Bad meta event

### ISSUE THREAD

**Issue by Moustiluigi** [timwedde/banana-split#4] opened 2021-05-06 14:51 UTC
I have been toying around with this software for the past few days and I encounter an error each time I try to use synthfluid (to convert the MIDI files into wav files).

`fluidsynth: error: Invalid length for SMPTE Offset meta event`

It's not the only error i encountered trying to use banana-split output files.
As an example, no python library that were meant to open MIDI file worked (whereas these same libraries worked with random MIDI files picked online).
Is there something I am missing ? Would the easiest way to fix this problem be to rerender the MIDI files so they have proper metadata, and if so, how?
Thank you,
MLR.

**Comment by timwedde** [comment] 2021-05-06 15:45
I can not reproduce this problem on my end.
Files generated by banana-split are proper MIDI files and open properly in my DAW (Logic X), have the proper signature when checked in a hex editor and can be converted to WAV via timidity as well.

Could you you share some of the files that produce the broken output?
I suspect there's something wonky in the input files that may cause this.

**Comment by Moustiluigi** [comment] 2021-05-06 22:25
Here are the files i'm using. I've tried to setup timidity but it doesn't seem to be as easy to use soundfont files on there.

[song_2.zip](https://github.com/timwedde/banana-split/files/6437918/song_2.zip)

**Comment by timwedde** [comment] 2021-05-06 22:46
I can not reproduce this on my end.
The file is processed correctly and outputs the split channels and tracks, as it is supposed to do.
The files open in Logic and I can pass them through timidity just fine as well.

I do get a popup telling me about SMPTE numbers being off (since the default is 25), but this is a valid MIDI command and thus within spec.

Aside from that, your input file contains these SMPTE-changing instructions, which are faithfully reproduced in the output as well. Hence I consider this as working-as-intended, since this is an artifact of the input file.

**Comment by timwedde** [comment] 2021-05-13 11:11
Closing for lack of response and since this may be resolved (due to the input being the issue).
If this issue still exists, feel free to comment here anyway.

**Closed as completed by timwedde** 2021-05-13 11:11 UTC
